### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by VizEll12** [d4n3436/Fergun#3] opened 2021-03-06 18:41 UTC
Hello. I downloaded your bot, didn't change anything, just uploaded the bot token and AI Dungeon. The mistake is that, continuing the story, the clues appear not one by one, but all at once, overlapping each other.

![21](https://user-images.githubusercontent.com/80172458/110217367-4fa38500-7ebc-11eb-90b2-29e3ee15d490.png)

**Comment by d4n3436** [comment] 2021-03-06 19:16
Hmm that shouldn't happen.
I think I the bug occurs [here](https://github.com/d4n3436/Fergun/blob/29e5edbd4834050796240939b410bdc91b85e102/src/Modules/AIDungeon.cs#L1263), when the method obtains the [localized tips](https://github.com/d4n3436/Fergun/blob/master/src/strings.resx#L1048-L1057) and splits them using `Environment.NewLine`.
What OS are you using to self-host the bot?

**Comment by lesyalovely** [comment] 2021-03-07 00:46
Tried using both Windows 10 Pro and Ubuntu 18.04 LTS

**Comment by VizEll12** [comment] 2021-03-07 00:47
Tried using both Windows 10 Pro and Ubuntu 18.04 LTS

**Comment by d4n3436** [comment] 2021-03-07 00:56
Well that's weird because I'm using exactly those two systems to develop Fergun and I can't reproduce the bug, but it should be easy to fix by changing `Environment.NewLine` to a consistent newline character that works on any OS.

**Comment by d4n3436** [comment] 2021-03-07 02:11
@VizEll12 The bug should be fixed with 4120668.

**Closed as completed by d4n3436** 2021-03-07 02:11 UTC
Labels: bug
